name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted]
    steps:
      - run: |
          echo Job triggered by ${{ github.event_name }} event.
      - run: |
          echo Runner OS: ${{ runner.os }}
      - run: |
          echo Branch: ${{ github.ref }}
          echo Repository: ${{ github.repository }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo Repository has been cloned successfully.
          echo Repo: ${{ github.repository }}
      - run: |
          echo Ready to test your code on the runner.
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          echo Job status: ${{ job.status }}
